### ISSUE TITLE
[NLContext runEventLoopAsync]; no known class method for selector 'runEventLoopAsync'

### ISSUE THREAD

**Issue by WolfieWerewolf** [domabo/nodeAppKit#1]
Guys... I'm very excited about this project.  I've been using Electron and not particularly enjoying the "Chromium" experience.  I think this is exactly what we need.  I've attempted unsuccessfully to compile but I'm receiving the above error.  Initially I made the mistake of opening the xproj instead of the workspace so I thought that would resolve it but it hasn't.  Looking through the code this method doesn't appear to exist?  I attempted pulling the nodeLike source and replacing the pod installed version but getting the same result.  I also tried pulling the zip from your website but that won't install the pods unless I perform the gem upgrade to beta 2.x.  That works but the error still exits.  

I would be very happy to get involved in this project and help out but just having a little trouble getting off the ground.  Oh, if I remove the mentioned line of code it will compile, I get the splash screen, but nothing else.  Any advice would be greatly appreciated.

Kind Regards

/W

**Comment by guybarnard** [comment]
Many thanks and glad to see you at the new site.  domabo/nodeappkit has been deprecated and replaced by nodekit-io/nodekit  [http://nodekit.io](http://nodekit.io).  Will eventually close this repository once all the code is in place in the new.
